# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TestProject1' do
  pod 'StreamingKit'
  
end

target 'TestProject1Tests' do

end

